### ISSUE TITLE
pod 安装不上

### ISSUE THREAD

**Issue by kelvin943** [JunyiXie/XJYChart#10]
Specs satisfying the `XJYChart (~> 1.1.0)` dependency were found, but they required a higher minimum deployment target

**Comment by JunyiXie** [comment]
In addition to the logic operators CocoaPods has an optimistic operator ~>:

'~> 0.1.2' Version 0.1.2 and the versions up to 0.2, not including 0.2 and higher
'~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher
'~> 0' Version 0 and higher, this is basically the same as not having it.

XJYChart don't have version [1.1.0, 1.2)...

Use:
` pod 'XJYChart` `

**Comment by kelvin943** [comment]
Use: pod 'XJYChart`  has the same problem

**Comment by kelvin943** [comment]
[!] Unable to satisfy the following requirements:

- `XJYChart` required by `Podfile`

Specs satisfying the `XJYChart` dependency were found, but they required a higher minimum deployment target.

**Comment by JunyiXie** [comment]
I set iOS platform iOS 9.1+
but I think iOS 8.0+ could work.
if you want , you can copy code and build by yourself.

In last version, I will change to iOS 8.0+
