### ISSUE TITLE
AreaLineChart类型的图表能显示背景上的虚线吗？

### ISSUE THREAD

**Issue by Kingson** [JunyiXie/XJYChart#16]
很高兴能看到这么好的作品，非常感谢。
提个小要求，能否在AreaLineChart类型的图表的背景上加上虚线吗？或者提示一下，主要看那个方法，我自己尝试改一下，再次感谢

**Comment by JunyiXie** [comment]
我已经加了哈 还没有 打包到 cocoapods 。
你可以试试 我的 Demo 看看是不是你想要的
