### ISSUE TITLE
您好, 使用cocoapods 一直install失败

### ISSUE THREAD

**Issue by huangyake** [JunyiXie/XJYChart#19]

**Comment by JunyiXie** [comment]
具体报错？

**Comment by huangyake** [comment]
Unable to satisfy the following requirements:

- `XJYChart` required by `Podfile`

Specs satisfying the `XJYChart` dependency were found, but they required a higher minimum deployment target.

**Comment by JunyiXie** [comment]
现在只支持 ios, "8.0" 及以上的
