### ISSUE TITLE
咨询图表

### ISSUE THREAD

**Issue by BenHuGZX** [JunyiXie/XJYChart#2]
你好，刚在github上看到你的点赞，进来一看刚好看到你那边有做图形这块，我想问下柱状图和折线图加点击卸载一起可以实现么？如果可以的话能不能加个QQ聊下呢？我这边学习下，比较急，谢谢了

**Comment by JunyiXie** [comment]
414623282

**Comment by JunyiXie** [comment]
可以实现的 我做到了点击识别，手工的...

**Comment by BenHuGZX** [comment]
好的，我加你




发自网易邮箱大师
在2017年03月27日 21:05，谢俊逸 写道：

可以实现的 我做到了点击识别，手工的...
