### ISSUE TITLE
用最新的xcode编译好多警告哎

### ISSUE THREAD

**Issue by WilliamIOS** [JunyiXie/XJYChart#23]
很喜欢你的这个东西
1、美观
2、保持更新
可惜好多警告～希望修改下下

**Comment by JunyiXie** [comment]
好的 等假期哈

**Comment by WilliamIOS** [comment]
嗯，还发现个问题，y轴的4个数字不精准，比右边第一象限的实际数值高了点。

**Comment by JunyiXie** [comment]
编译警告已经修复了。
y轴坐标使用label做的，由于视图边界的原因，很难做到完全对齐
