### ISSUE TITLE
Y轴是否可以隐藏？

### ISSUE THREAD

**Issue by TomasPangzi** [JunyiXie/XJYChart#26]

**Comment by TomasPangzi** [comment]
我看了源码了。目前还没实现整个功能。是否考虑configulation加个配置的参数可将ordinateView去掉？

**Comment by JunyiXie** [comment]
源码都看了 可以帮忙实现一下呗

**Comment by TomasPangzi** [comment]
@JunyiXie 等我这阵子忙完了我就拉个分支来实现

**Comment by JunyiXie** [comment]
thanks

**Comment by dong136279559** [comment]
我们需求也是 隐藏y轴 能帮忙实现下吗?

**Comment by Kingson** [comment]
可以隐藏了

**Comment by JunyiXie** [comment]
周末搞一下
下一个版本支持

**Comment by dong136279559** [comment]
作者大兄弟呢,这几个周末过去了.....

**Comment by JunyiXie** [comment]
人在头条 大小周 ...
2.5.0
https://github.com/JunyiXie/XJYChart/blob/a7f3a5af819ccddb7ebdb86d3fa8ec79a4ebf1fa/XJYChart/Configuration/XBaseChartConfiguration.h#L18
