### ISSUE TITLE
柱状图能不能支持负值。项目有这方面需要。一改成负值，直接闪退

### ISSUE THREAD

**Issue by lp380490944** [JunyiXie/XJYChart#3]
![http://ofotg48ff.bkt.clouddn.com/17-4-17/69068174-file_1492410498906_16cf1.png](http://ofotg48ff.bkt.clouddn.com/17-4-17/69068174-file_1492410498906_16cf1.png)

**Comment by lp380490944** [comment]
![Uploading 5A906BA2-A087-4DF3-8AB6-5137414B226D.png…]()

**Comment by lp380490944** [comment]
![Uploading 4B226D.png…]()
![Uploading 4B226D.png…]()

**Comment by JunyiXie** [comment]
好的  我会新开个图 来修复这个问题。本来这个柱状图 是没打算做这个功能的

**Comment by JunyiXie** [comment]
新增 XXPositiveNegativeBarChart 
希望能解决你的问题
QAQ
