### ISSUE TITLE
另外目前只是提供了初始化时设置frame的方法

### ISSUE THREAD

**Issue by MrVking** [JunyiXie/XJYChart#31]
目前只是提供了初始化时设置frame的方法，没有可以另外设置frame的方法，例如在xib中使用就非常不方便，使用自动布局也是很不方便，例如masonry

**Comment by MrVking** [comment]
希望作者好好完善一下该库，绝对可以比Charts和PNChart好用，前者OC集成太麻烦了，而且库相当庞大，很占包的体积，后者BUG太多，提问作者也不回，无积极完善的意图

**Comment by JunyiXie** [comment]
可以哈 我研究下xib怎么玩 我没怎么用过.. 如果你有时间 并且熟悉xib 欢迎你贡献一下代码 🤩

**Comment by MrVking** [comment]
装在xib中的容器中就可以了
