### ISSUE TITLE
能否增加点击图表显示/隐藏数值的功能？

### ISSUE THREAD

**Issue by Kingson** [JunyiXie/XJYChart#38]
能否增加点击图表显示/隐藏数值的功能？

**Comment by Kingson** [comment]
@JunyiXie 太感谢了

**Comment by JunyiXie** [comment]
现在2.4.0 支持 LineChart 
https://github.com/JunyiXie/XJYChart/blob/b85e3e704ac84b233561800eb5786efa04bdbd9f/XJYChart/Configuration/LineChartConfiguration/XLineChartConfiguration.h#L35
