### ISSUE TITLE
数据随时间变化的情况

### ISSUE THREAD

**Issue by whatsbug** [JunyiXie/XJYChart#7]
请问如果数据会随着时间变化的情况，怎么解决？比如汽车的加速度，每隔一秒测量一次加速度，随着时间的增长，加速度会变化，这种情况用折线图如何表示？

**Comment by JunyiXie** [comment]
1. 性能因素不是瓶颈,那就重新载入新的数据。
2. 性能受限，我建议从头开始做一个新的图表，新的数据 采用重绘部分数据的方式绘制。

XJYChart是静态数据的，如果做动态数据更新的 我觉得找股票方面的图 稍微修改下就可以的。

**Comment by whatsbug** [comment]
haode thanks ~
