### ISSUE TITLE
最低支持的系统版本是多少？

### ISSUE THREAD

**Issue by dagundejuzi** [JunyiXie/XJYChart#9]
项目支持的最低版本是8.0。
pod 报错： Specs satisfying the `XJYChart` dependency were found, but they required a higher minimum deployment target.

**Comment by JunyiXie** [comment]
8 应该也是支持的 但是我Pod 的版本是九，

**Comment by JunyiXie** [comment]
你可以自己用源码打包

**Comment by dagundejuzi** [comment]
我去集了 PNChart。 PNLineChart 的 x 轴 lable 和几个chartMargin的有点小问题。
PNChart 和这个的饼图，值的 lable都是在饼内？有在外面的吗？

**Comment by JunyiXie** [comment]
这个并不复杂。。。 你可以尝试改改源码
